common:
    lid_topic:  "/livox/lidar"

preprocess:
    lidar_type: 1                # Livox series LiDAR
    feature_extract_en: false
    scan_line: 6
    blind: 1
    point_filter_num: 3

initialization:
    cut_frame: true
    cut_frame_num: 5
    cut_frame_init_num: 5

mapping:
    filter_size_surf: 0.3
    filter_size_map: 0.3
    gyr_cov: 1.01
    acc_cov: 1.01
    det_range: 100.0
    cov_lidar: 0.001
    max_iteration: 20
    max_undistort: 5
    cube_side_length: 2000

publish:
    path_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: false  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
